[package]
name = "parnassum"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]

[dependencies]
rouille = "3.0.0"
tera = "0.11.20"
rusqlite = "0.16.0"
ring = "0.13.5"
base64 = "0.10.0"
